import { append, detailTable } from '/governance/memory-presentation.js';

const ENDPOINT = '/governance/api/v1/operations/retention';
const OPAQUE = /^[A-Za-z0-9_-]{43}$/;
const DIGEST = /^[0-9a-f]{64}$/;
const POLICY_KEYS = ['rawEventsDays', 'chatMessagesDays', 'auditLogDays', 'disabledDeletedMemoryDays', 'eventProcessingFailuresDays'];
const EFFECT_KEYS = ['rawEventsDeleted', 'modelInvocationSourcesDeleted', 'chatMessagesDeleted', 'auditLogDeleted', 'eventProcessingFailuresDeleted', 'memoriesPurged', 'actionMemoryLinksCleared', 'memorySourcesDeleted', 'memoryRevisionsDeleted', 'memoryFtsRowsDeleted'];
function exact(value, keys) { return Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key))); }
function integer(value) { return Number.isSafeInteger(value) && value >= 0; }
function iso(value) { if (typeof value !== 'string') return false; const time = Date.parse(value); return Number.isFinite(time) && new Date(time).toISOString() === value; }
function preview(value, now) {
  if (!exact(value, ['action', 'currentState', 'contractVersion', 'asOf', 'configuredPolicy', 'memoryStates', 'effects', 'zeroMeansForever', 'irreversible', 'previewDigest', 'previewHandle', 'previewExpiresAt']) || value.action !== 'apply_configured_retention' || typeof value.currentState !== 'string' || !DIGEST.test(value.currentState) || value.contractVersion !== 1 || !iso(value.asOf) || !exact(value.configuredPolicy, POLICY_KEYS) || !POLICY_KEYS.every((key) => integer(value.configuredPolicy[key])) || !Array.isArray(value.memoryStates) || value.memoryStates.join(',') !== 'rejected,disabled,deleted' || !exact(value.effects, EFFECT_KEYS) || !EFFECT_KEYS.every((key) => integer(value.effects[key])) || value.zeroMeansForever !== true || !exact(value.irreversible, ['hardDelete', 'rollbackAvailable', 'boundary']) || value.irreversible.hardDelete !== true || value.irreversible.rollbackAvailable !== false || value.irreversible.boundary !== 'verified_backup_recommended' || !DIGEST.test(value.previewDigest) || !OPAQUE.test(value.previewHandle) || !integer(value.previewExpiresAt) || value.previewExpiresAt <= now) return null;
  return value;
}
function result(value) { return exact(value, ['action', 'status', 'contractVersion', 'appliedAt', 'configuredPolicy', 'memoryStates', 'effects', 'zeroMeansForever', 'irreversible']) && value.action === 'apply_configured_retention' && value.status === 'applied' && value.contractVersion === 1 && iso(value.appliedAt) && exact(value.configuredPolicy, POLICY_KEYS) && POLICY_KEYS.every((key) => integer(value.configuredPolicy[key])) && Array.isArray(value.memoryStates) && value.memoryStates.join(',') === 'rejected,disabled,deleted' && exact(value.effects, EFFECT_KEYS) && EFFECT_KEYS.every((key) => integer(value.effects[key])) && value.zeroMeansForever === true && exact(value.irreversible, ['hardDelete', 'rollbackAvailable', 'boundary']) && value.irreversible.hardDelete === true && value.irreversible.rollbackAvailable === false && value.irreversible.boundary === 'verified_backup_recommended' ? value : null; }
function rows(table, values) { table.replaceChildren(); for (const [label, primary, secondary] of values) { const row = append(table, 'div'); append(row, 'dt', {}, label); const cell = append(row, 'dd'); append(cell, 'span', { class: 'worker-heartbeat-primary' }, primary); append(cell, 'span', { class: 'worker-heartbeat-secondary' }, secondary); } }

export function createRetentionPanel(parent, setHidden, mutate, expired, announce, clearOperationsAuthority) {
  const panel = append(parent, 'section', { id: 'operations-retention', class: 'memory-scope-band', 'aria-labelledby': 'operations-retention-title' });
  append(panel, 'h2', { id: 'operations-retention-title' }, 'Configured retention');
  append(panel, 'p', {}, 'Hard-delete terminal memory and expired records. A verified backup is recommended; it is not a program prerequisite.');
  const previewButton = append(panel, 'button', { id: 'operations-retention-preview-button', class: 'button button-secondary', type: 'button' }, 'Preview configured retention');
  const surface = append(panel, 'section', { id: 'operations-retention-preview', hidden: '' });
  const table = detailTable(surface, 'Retention preview', ['Policy', 'Memory states', 'Effects', 'Boundary']);
  const confirmButton = append(surface, 'button', { id: 'operations-retention-confirm-button', class: 'button button-primary', type: 'button', disabled: '' }, 'Confirm retention');
  let authority = null; let sequence = 0; let timer = null;
  function clear() { sequence += 1; if (timer !== null) window.clearTimeout(timer); timer = null; authority = null; confirmButton.disabled = true; previewButton.disabled = false; setHidden(surface, true); }
  async function doPreview() { clear(); clearOperationsAuthority(); previewButton.disabled = true; const current = ++sequence; const response = await mutate(ENDPOINT, { action: 'apply_configured_retention' }); if (current !== sequence) return; if (response.status === 401) return expired(); const normalized = response.status === 201 ? preview(response.body, Date.now()) : null; if (!normalized) { previewButton.disabled = false; announce('Retention preview unavailable.'); return; } rows(table, [['Policy', String(normalized.configuredPolicy.rawEventsDays) + ' raw / ' + String(normalized.configuredPolicy.chatMessagesDays) + ' chat days', String(normalized.configuredPolicy.auditLogDays) + ' audit days'], ['Memory states', 'rejected / disabled / deleted', 'Active memory is excluded'], ['Effects', String(normalized.effects.memoriesPurged) + ' memories', String(normalized.effects.chatMessagesDeleted) + ' chats / ' + String(normalized.effects.rawEventsDeleted) + ' raw events'], ['Boundary', 'Hard delete; no rollback', 'Backup recommended']]); authority = { handle: normalized.previewHandle, expiresAt: normalized.previewExpiresAt }; previewButton.disabled = true; confirmButton.disabled = false; setHidden(surface, false); timer = window.setTimeout(() => { authority = null; confirmButton.disabled = true; previewButton.disabled = false; setHidden(surface, true); announce('Retention preview expired.'); }, Math.min(normalized.previewExpiresAt - Date.now(), 2147483647)); announce('Retention preview ready.'); }
  async function doConfirm() { const retained = authority; if (!retained || confirmButton.disabled || retained.expiresAt <= Date.now()) { clear(); return; } authority = null; confirmButton.disabled = true; if (timer !== null) window.clearTimeout(timer); timer = null; const current = ++sequence; const response = await mutate(ENDPOINT + '/confirm', { confirm: true, previewHandle: retained.handle }); if (current !== sequence) return; if (response.status === 401) return expired(); const normalized = response.status === 200 ? result(response.body) : null; if (!normalized) { previewButton.disabled = false; announce('Retention confirmation unavailable; preview again.'); return; } rows(table, [['Policy', 'Configured retention applied', 'At ' + normalized.appliedAt], ['Memory states', 'rejected / disabled / deleted', 'Active memory excluded'], ['Effects', String(normalized.effects.memoriesPurged) + ' memories', String(normalized.effects.rawEventsDeleted) + ' raw events'], ['Boundary', 'Hard delete; no rollback', 'Backup recommended']]); setHidden(surface, false); announce('Configured retention applied.'); }
  previewButton.addEventListener('click', () => void doPreview()); confirmButton.addEventListener('click', () => void doConfirm());
  return { clear, reset: clear };
}
